%%{init: {'theme':'dark', 'themeVariables': { 'fontSize':'16px', 'fontFamily':'arial'}}}%%
flowchart LR

  %% Dataset
  subgraph DatasetBox [Dataset]
    Dataset[(ADReSSo-2021)]
  end

  %% Preprocessing
  subgraph Preprocessing [Preprocessing]
    direction TB
    AudioProc[Audio Processing]
    STT[Speech to Text]
  end

  %% Feature extraction
  subgraph FeatureExtraction [Feature Extraction]
    direction TB
    Acoustic[Acoustic Feature]
    Linguistic[Linguistic Feature]
  end

  %% Classification
  subgraph Classification [Classification]
    Classifier["RF<br/>XGB<br/>MLP"]
  end

  %% Flows
  Dataset --> AudioProc
  Dataset --> STT

  AudioProc --> Acoustic
  STT --> Linguistic

  Acoustic --> Classifier
  Linguistic --> Classifier
